# Generated by Django 5.2.5 on 2025-09-11 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('accessories', 'Accessories')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('clothes_size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5, null=True)),
                ('shoe_size', models.CharField(blank=True, choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='shop',
        ),
    ]
